// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approvals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchApproveItems = `-- name: BatchApproveItems :exec
UPDATE approval_items
SET status = 'approved', batch_id = $1, reviewed_at = now(), reviewed_by = $2
WHERE tenant_id = $3 AND id = ANY($4::uuid[]) AND status IN ('pending', 'needs_review')
`

type BatchApproveItemsParams struct {
	BatchID    pgtype.UUID   `json:"batch_id"`
	ReviewedBy pgtype.UUID   `json:"reviewed_by"`
	TenantID   pgtype.UUID   `json:"tenant_id"`
	Column4    []pgtype.UUID `json:"column_4"`
}

func (q *Queries) BatchApproveItems(ctx context.Context, arg BatchApproveItemsParams) error {
	_, err := q.db.Exec(ctx, batchApproveItems,
		arg.BatchID,
		arg.ReviewedBy,
		arg.TenantID,
		arg.Column4,
	)
	return err
}

const countFlaggedInBatch = `-- name: CountFlaggedInBatch :one
SELECT COUNT(*) FROM approval_items
WHERE tenant_id = $1 AND id = ANY($2::uuid[]) AND flagged = true
`

type CountFlaggedInBatchParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	Column2  []pgtype.UUID `json:"column_2"`
}

func (q *Queries) CountFlaggedInBatch(ctx context.Context, arg CountFlaggedInBatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFlaggedInBatch, arg.TenantID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovalBatch = `-- name: CreateApprovalBatch :one
INSERT INTO approval_batches (tenant_id, approved_by, order_count, flagged_count)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, approved_by, approved_at, order_count, flagged_count
`

type CreateApprovalBatchParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ApprovedBy   pgtype.UUID `json:"approved_by"`
	OrderCount   int32       `json:"order_count"`
	FlaggedCount int32       `json:"flagged_count"`
}

func (q *Queries) CreateApprovalBatch(ctx context.Context, arg CreateApprovalBatchParams) (ApprovalBatch, error) {
	row := q.db.QueryRow(ctx, createApprovalBatch,
		arg.TenantID,
		arg.ApprovedBy,
		arg.OrderCount,
		arg.FlaggedCount,
	)
	var i ApprovalBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.OrderCount,
		&i.FlaggedCount,
	)
	return i, err
}

const createProtocol = `-- name: CreateProtocol :one
INSERT INTO protocols (tenant_id, name, procedure_name, standard_dosage, max_lab_age_days, requires_established_patient)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, procedure_name, standard_dosage, max_lab_age_days, requires_established_patient, active, created_at, updated_at
`

type CreateProtocolParams struct {
	TenantID                   pgtype.UUID `json:"tenant_id"`
	Name                       string      `json:"name"`
	ProcedureName              string      `json:"procedure_name"`
	StandardDosage             pgtype.Text `json:"standard_dosage"`
	MaxLabAgeDays              int32       `json:"max_lab_age_days"`
	RequiresEstablishedPatient bool        `json:"requires_established_patient"`
}

func (q *Queries) CreateProtocol(ctx context.Context, arg CreateProtocolParams) (Protocol, error) {
	row := q.db.QueryRow(ctx, createProtocol,
		arg.TenantID,
		arg.Name,
		arg.ProcedureName,
		arg.StandardDosage,
		arg.MaxLabAgeDays,
		arg.RequiresEstablishedPatient,
	)
	var i Protocol
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ProcedureName,
		&i.StandardDosage,
		&i.MaxLabAgeDays,
		&i.RequiresEstablishedPatient,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingApprovalItems = `-- name: ListPendingApprovalItems :many
SELECT id, batch_id, tenant_id, emr_order_id, patient_id, patient_name,
       procedure_name, dosage, staff_name, order_date, flagged, flag_reasons,
       status, reviewed_at, reviewed_by, created_at
FROM approval_items
WHERE tenant_id = $1 AND status IN ('pending', 'needs_review')
ORDER BY flagged DESC, order_date ASC
`

func (q *Queries) ListPendingApprovalItems(ctx context.Context, tenantID pgtype.UUID) ([]ApprovalItem, error) {
	rows, err := q.db.Query(ctx, listPendingApprovalItems, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalItem{}
	for rows.Next() {
		var i ApprovalItem
		if err := rows.Scan(
			&i.ID,
			&i.BatchID,
			&i.TenantID,
			&i.EmrOrderID,
			&i.PatientID,
			&i.PatientName,
			&i.ProcedureName,
			&i.Dosage,
			&i.StaffName,
			&i.OrderDate,
			&i.Flagged,
			&i.FlagReasons,
			&i.Status,
			&i.ReviewedAt,
			&i.ReviewedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProtocols = `-- name: ListProtocols :many
SELECT id, tenant_id, name, procedure_name, standard_dosage, max_lab_age_days,
       requires_established_patient, active, created_at, updated_at
FROM protocols
WHERE tenant_id = $1 AND active = true
`

func (q *Queries) ListProtocols(ctx context.Context, tenantID pgtype.UUID) ([]Protocol, error) {
	rows, err := q.db.Query(ctx, listProtocols, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Protocol{}
	for rows.Next() {
		var i Protocol
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ProcedureName,
			&i.StandardDosage,
			&i.MaxLabAgeDays,
			&i.RequiresEstablishedPatient,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertApprovalItem = `-- name: UpsertApprovalItem :exec
INSERT INTO approval_items (tenant_id, emr_order_id, patient_id, patient_name, procedure_name, dosage, staff_name, order_date, flagged, flag_reasons, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (tenant_id, emr_order_id) DO UPDATE SET
  patient_name = EXCLUDED.patient_name,
  dosage = EXCLUDED.dosage,
  staff_name = EXCLUDED.staff_name,
  flagged = EXCLUDED.flagged,
  flag_reasons = EXCLUDED.flag_reasons,
  status = EXCLUDED.status
`

type UpsertApprovalItemParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	EmrOrderID    string      `json:"emr_order_id"`
	PatientID     string      `json:"patient_id"`
	PatientName   string      `json:"patient_name"`
	ProcedureName string      `json:"procedure_name"`
	Dosage        pgtype.Text `json:"dosage"`
	StaffName     pgtype.Text `json:"staff_name"`
	OrderDate     pgtype.Date `json:"order_date"`
	Flagged       bool        `json:"flagged"`
	FlagReasons   []byte      `json:"flag_reasons"`
	Status        string      `json:"status"`
}

func (q *Queries) UpsertApprovalItem(ctx context.Context, arg UpsertApprovalItemParams) error {
	_, err := q.db.Exec(ctx, upsertApprovalItem,
		arg.TenantID,
		arg.EmrOrderID,
		arg.PatientID,
		arg.PatientName,
		arg.ProcedureName,
		arg.Dosage,
		arg.StaffName,
		arg.OrderDate,
		arg.Flagged,
		arg.FlagReasons,
		arg.Status,
	)
	return err
}
