// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"encoding/json"

	"github.com/jackc/pgtype"
)

type ApprovalBatch struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	OrderCount   int64              `json:"order_count"`
	FlaggedCount int64              `json:"flagged_count"`
}

type ApprovalItem struct {
	ID            pgtype.UUID        `json:"id"`
	BatchID       pgtype.UUID        `json:"batch_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	EmrOrderID    string             `json:"emr_order_id"`
	PatientID     string             `json:"patient_id"`
	PatientName   string             `json:"patient_name"`
	ProcedureName string             `json:"procedure_name"`
	Dosage        pgtype.Text        `json:"dosage"`
	StaffName     pgtype.Text        `json:"staff_name"`
	OrderDate     pgtype.Date        `json:"order_date"`
	Flagged       bool               `json:"flagged"`
	FlagReasons   json.RawMessage    `json:"flag_reasons"`
	Status        string             `json:"status"`
	ReviewedAt    pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy    pgtype.UUID        `json:"reviewed_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	EncounterID   pgtype.Text        `json:"encounter_id"`
	DepartmentID  pgtype.Text        `json:"department_id"`
	OrderType     pgtype.Text        `json:"order_type"`
}

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Text        `json:"resource_id"`
	Details      json.RawMessage    `json:"details"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Protocol struct {
	ID                         pgtype.UUID        `json:"id"`
	TenantID                   pgtype.UUID        `json:"tenant_id"`
	Name                       string             `json:"name"`
	ProcedureName              string             `json:"procedure_name"`
	StandardDosage             pgtype.Text        `json:"standard_dosage"`
	MaxLabAgeDays              int64              `json:"max_lab_age_days"`
	RequiresEstablishedPatient bool               `json:"requires_established_patient"`
	Active                     bool               `json:"active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ScribeFeedback struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Section   string             `json:"section"`
	Category  string             `json:"category"`
	Body      string             `json:"body"`
	UserID    pgtype.UUID        `json:"user_id"`
	At        pgtype.Timestamptz `json:"at"`
}

type ScribeSectionApproval struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Section   string             `json:"section"`
	Action    string             `json:"action"`
	UserID    pgtype.UUID        `json:"user_id"`
	At        pgtype.Timestamptz `json:"at"`
}

type ScribeSectionEdit struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Section   string             `json:"section"`
	Content   json.RawMessage    `json:"content"`
	EditedBy  pgtype.UUID        `json:"edited_by"`
	At        pgtype.Timestamptz `json:"at"`
}

type ScribeSession struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	UserID           pgtype.UUID        `json:"user_id"`
	PatientID        string             `json:"patient_id"`
	EncounterID      string             `json:"encounter_id"`
	DepartmentID     string             `json:"department_id"`
	Status           string             `json:"status"`
	Transcript       pgtype.Text        `json:"transcript"`
	AiOutput         json.RawMessage    `json:"ai_output"`
	ErrorMessage     pgtype.Text        `json:"error_message"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	StoppedAt        pgtype.Timestamptz `json:"stopped_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	SentToEhrAt      pgtype.Timestamptz `json:"sent_to_ehr_at"`
	SentToEhrBy      pgtype.UUID        `json:"sent_to_ehr_by"`
	RejectedAt       pgtype.Timestamptz `json:"rejected_at"`
	RejectedBy       pgtype.UUID        `json:"rejected_by"`
	AppointmentID    string             `json:"appointment_id"`
	Label            string             `json:"label"`
	DocumentFilename string             `json:"document_filename"`
}

type ScribeUsageEvent struct {
	ID                      pgtype.UUID        `json:"id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	EventType               string             `json:"event_type"`
	Provider                string             `json:"provider"`
	Operation               string             `json:"operation"`
	ModelID                 pgtype.Text        `json:"model_id"`
	ExternalJobID           pgtype.Text        `json:"external_job_id"`
	AudioDurationSeconds    pgtype.Numeric     `json:"audio_duration_seconds"`
	BillableDurationSeconds pgtype.Int4        `json:"billable_duration_seconds"`
	InputTokens             pgtype.Int4        `json:"input_tokens"`
	OutputTokens            pgtype.Int4        `json:"output_tokens"`
	TotalTokens             pgtype.Int4        `json:"total_tokens"`
	EstimatedCostMicros     int64              `json:"estimated_cost_micros"`
	ActualCostMicros        pgtype.Int8        `json:"actual_cost_micros"`
	Currency                string             `json:"currency"`
	PricingSource           string             `json:"pricing_source"`
	RateSnapshot            json.RawMessage    `json:"rate_snapshot"`
	Metadata                json.RawMessage    `json:"metadata"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID                    pgtype.UUID        `json:"id"`
	Name                  string             `json:"name"`
	AthenaPracticeID      pgtype.Text        `json:"athena_practice_id"`
	AthenaAccessTokenEnc  pgtype.Text        `json:"athena_access_token_enc"`
	AthenaRefreshTokenEnc pgtype.Text        `json:"athena_refresh_token_enc"`
	AthenaTokenExpiresAt  pgtype.Timestamptz `json:"athena_token_expires_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Name         string             `json:"name"`
	MfaSecret    pgtype.Text        `json:"mfa_secret"`
	MfaEnabled   bool               `json:"mfa_enabled"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
