// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ocr.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentScribeSession = `-- name: CreateDocumentScribeSession :one
INSERT INTO scribe_sessions (tenant_id, user_id, patient_id, encounter_id, appointment_id, department_id, transcript, status, document_id)
VALUES ($1, $2, $3, '', $4, $5, $6, 'processing', $7)
RETURNING id, tenant_id, user_id, patient_id, encounter_id, appointment_id, department_id, label, status,
          transcript, ai_output, error_message, started_at, stopped_at, completed_at, created_at
`

type CreateDocumentScribeSessionParams struct {
	TenantID      pgtype.UUID `json:"tenant_id"`
	UserID        pgtype.UUID `json:"user_id"`
	PatientID     string      `json:"patient_id"`
	AppointmentID string      `json:"appointment_id"`
	DepartmentID  string      `json:"department_id"`
	Transcript    pgtype.Text `json:"transcript"`
	DocumentID    pgtype.UUID `json:"document_id"`
}

type CreateDocumentScribeSessionRow struct {
	ID            pgtype.UUID        `json:"id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	PatientID     string             `json:"patient_id"`
	EncounterID   string             `json:"encounter_id"`
	AppointmentID string             `json:"appointment_id"`
	DepartmentID  string             `json:"department_id"`
	Label         string             `json:"label"`
	Status        string             `json:"status"`
	Transcript    pgtype.Text        `json:"transcript"`
	AiOutput      []byte             `json:"ai_output"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	StoppedAt     pgtype.Timestamptz `json:"stopped_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateDocumentScribeSession(ctx context.Context, arg CreateDocumentScribeSessionParams) (CreateDocumentScribeSessionRow, error) {
	row := q.db.QueryRow(ctx, createDocumentScribeSession,
		arg.TenantID,
		arg.UserID,
		arg.PatientID,
		arg.AppointmentID,
		arg.DepartmentID,
		arg.Transcript,
		arg.DocumentID,
	)
	var i CreateDocumentScribeSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PatientID,
		&i.EncounterID,
		&i.AppointmentID,
		&i.DepartmentID,
		&i.Label,
		&i.Status,
		&i.Transcript,
		&i.AiOutput,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOCRDocument = `-- name: CreateOCRDocument :one
INSERT INTO ocr_documents (tenant_id, user_id, original_filename, content_type, status)
VALUES ($1, $2, $3, $4, 'uploaded')
RETURNING id, tenant_id, user_id, original_filename, content_type, status,
          error_message, extracted_text, scribe_session_id, created_at, extracted_at
`

type CreateOCRDocumentParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	UserID           pgtype.UUID `json:"user_id"`
	OriginalFilename string      `json:"original_filename"`
	ContentType      string      `json:"content_type"`
}

func (q *Queries) CreateOCRDocument(ctx context.Context, arg CreateOCRDocumentParams) (OcrDocument, error) {
	row := q.db.QueryRow(ctx, createOCRDocument,
		arg.TenantID,
		arg.UserID,
		arg.OriginalFilename,
		arg.ContentType,
	)
	var i OcrDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Status,
		&i.ErrorMessage,
		&i.ExtractedText,
		&i.ScribeSessionID,
		&i.CreatedAt,
		&i.ExtractedAt,
	)
	return i, err
}

const deleteOCRDocument = `-- name: DeleteOCRDocument :execrows
DELETE FROM ocr_documents
WHERE id = $1 AND tenant_id = $2
`

type DeleteOCRDocumentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteOCRDocument(ctx context.Context, arg DeleteOCRDocumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOCRDocument, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOCRDocument = `-- name: GetOCRDocument :one
SELECT id, tenant_id, user_id, original_filename, content_type, status,
       error_message, extracted_text, scribe_session_id, created_at, extracted_at
FROM ocr_documents
WHERE id = $1 AND tenant_id = $2
`

type GetOCRDocumentParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetOCRDocument(ctx context.Context, arg GetOCRDocumentParams) (OcrDocument, error) {
	row := q.db.QueryRow(ctx, getOCRDocument, arg.ID, arg.TenantID)
	var i OcrDocument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.OriginalFilename,
		&i.ContentType,
		&i.Status,
		&i.ErrorMessage,
		&i.ExtractedText,
		&i.ScribeSessionID,
		&i.CreatedAt,
		&i.ExtractedAt,
	)
	return i, err
}

const listOCRDocuments = `-- name: ListOCRDocuments :many
SELECT id, tenant_id, user_id, original_filename, content_type, status,
       error_message, extracted_text, scribe_session_id, created_at, extracted_at
FROM ocr_documents
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT 50
`

func (q *Queries) ListOCRDocuments(ctx context.Context, tenantID pgtype.UUID) ([]OcrDocument, error) {
	rows, err := q.db.Query(ctx, listOCRDocuments, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OcrDocument{}
	for rows.Next() {
		var i OcrDocument
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.OriginalFilename,
			&i.ContentType,
			&i.Status,
			&i.ErrorMessage,
			&i.ExtractedText,
			&i.ScribeSessionID,
			&i.CreatedAt,
			&i.ExtractedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOCRDocumentScribeSession = `-- name: SetOCRDocumentScribeSession :exec
UPDATE ocr_documents
SET scribe_session_id = $3
WHERE id = $1 AND tenant_id = $2
`

type SetOCRDocumentScribeSessionParams struct {
	ID              pgtype.UUID `json:"id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	ScribeSessionID pgtype.UUID `json:"scribe_session_id"`
}

func (q *Queries) SetOCRDocumentScribeSession(ctx context.Context, arg SetOCRDocumentScribeSessionParams) error {
	_, err := q.db.Exec(ctx, setOCRDocumentScribeSession, arg.ID, arg.TenantID, arg.ScribeSessionID)
	return err
}

const updateOCRDocumentError = `-- name: UpdateOCRDocumentError :exec
UPDATE ocr_documents
SET status = 'error', error_message = $3
WHERE id = $1 AND tenant_id = $2
`

type UpdateOCRDocumentErrorParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateOCRDocumentError(ctx context.Context, arg UpdateOCRDocumentErrorParams) error {
	_, err := q.db.Exec(ctx, updateOCRDocumentError, arg.ID, arg.TenantID, arg.ErrorMessage)
	return err
}

const updateOCRDocumentExtracted = `-- name: UpdateOCRDocumentExtracted :exec
UPDATE ocr_documents
SET status = 'extracted', extracted_text = $3, extracted_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateOCRDocumentExtractedParams struct {
	ID            pgtype.UUID `json:"id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
	ExtractedText pgtype.Text `json:"extracted_text"`
}

func (q *Queries) UpdateOCRDocumentExtracted(ctx context.Context, arg UpdateOCRDocumentExtractedParams) error {
	_, err := q.db.Exec(ctx, updateOCRDocumentExtracted, arg.ID, arg.TenantID, arg.ExtractedText)
	return err
}

const updateOCRDocumentExtracting = `-- name: UpdateOCRDocumentExtracting :exec
UPDATE ocr_documents
SET status = 'extracting'
WHERE id = $1 AND tenant_id = $2
`

type UpdateOCRDocumentExtractingParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) UpdateOCRDocumentExtracting(ctx context.Context, arg UpdateOCRDocumentExtractingParams) error {
	_, err := q.db.Exec(ctx, updateOCRDocumentExtracting, arg.ID, arg.TenantID)
	return err
}
