// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scribe_approvals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSessionSectionStates = `-- name: GetSessionSectionStates :many
SELECT DISTINCT ON (a.section)
    a.section, a.action, a.user_id, a.at, u.name AS user_name
FROM scribe_section_approvals a
JOIN users u ON u.id = a.user_id
WHERE a.session_id = $1
ORDER BY a.section, a.at DESC
`

type GetSessionSectionStatesRow struct {
	Section  string             `json:"section"`
	Action   string             `json:"action"`
	UserID   pgtype.UUID        `json:"user_id"`
	At       pgtype.Timestamptz `json:"at"`
	UserName string             `json:"user_name"`
}

// Latest event per section for one session, joined to the actor's display name.
func (q *Queries) GetSessionSectionStates(ctx context.Context, sessionID pgtype.UUID) ([]GetSessionSectionStatesRow, error) {
	rows, err := q.db.Query(ctx, getSessionSectionStates, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionSectionStatesRow{}
	for rows.Next() {
		var i GetSessionSectionStatesRow
		if err := rows.Scan(
			&i.Section,
			&i.Action,
			&i.UserID,
			&i.At,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSectionApproval = `-- name: RecordSectionApproval :exec
INSERT INTO scribe_section_approvals (session_id, section, action, user_id)
VALUES ($1, $2, $3, $4)
`

type RecordSectionApprovalParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Section   string      `json:"section"`
	Action    string      `json:"action"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RecordSectionApproval(ctx context.Context, arg RecordSectionApprovalParams) error {
	_, err := q.db.Exec(ctx, recordSectionApproval,
		arg.SessionID,
		arg.Section,
		arg.Action,
		arg.UserID,
	)
	return err
}
