// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scribe_approvals.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgtype"
)

const getSessionSectionEdits = `-- name: GetSessionSectionEdits :many
SELECT section, content, edited_by, at
FROM (
    SELECT
        section, content, edited_by, at,
        row_number() OVER (PARTITION BY section ORDER BY at DESC) AS rn
    FROM scribe_section_edits
    WHERE session_id = ?1
)
WHERE rn = 1
ORDER BY section
`

type GetSessionSectionEditsRow struct {
	Section  string             `json:"section"`
	Content  json.RawMessage    `json:"content"`
	EditedBy pgtype.UUID        `json:"edited_by"`
	At       pgtype.Timestamptz `json:"at"`
}

// Latest edit per section for one session.
func (q *Queries) GetSessionSectionEdits(ctx context.Context, sessionID pgtype.UUID) ([]GetSessionSectionEditsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionSectionEdits, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionSectionEditsRow{}
	for rows.Next() {
		var i GetSessionSectionEditsRow
		if err := rows.Scan(
			&i.Section,
			&i.Content,
			&i.EditedBy,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionSectionStates = `-- name: GetSessionSectionStates :many
SELECT section, action, user_id, at, user_name
FROM (
    SELECT
        a.section, a.action, a.user_id, a.at, u.name AS user_name,
        row_number() OVER (PARTITION BY a.section ORDER BY a.at DESC) AS rn
    FROM scribe_section_approvals a
    JOIN users u ON u.id = a.user_id
    WHERE a.session_id = ?1
)
WHERE rn = 1
ORDER BY section
`

type GetSessionSectionStatesRow struct {
	Section  string             `json:"section"`
	Action   string             `json:"action"`
	UserID   pgtype.UUID        `json:"user_id"`
	At       pgtype.Timestamptz `json:"at"`
	UserName string             `json:"user_name"`
}

// Latest event per section for one session, joined to the actor's display name.
func (q *Queries) GetSessionSectionStates(ctx context.Context, sessionID pgtype.UUID) ([]GetSessionSectionStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionSectionStates, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionSectionStatesRow{}
	for rows.Next() {
		var i GetSessionSectionStatesRow
		if err := rows.Scan(
			&i.Section,
			&i.Action,
			&i.UserID,
			&i.At,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSectionApproval = `-- name: RecordSectionApproval :exec
INSERT INTO scribe_section_approvals (session_id, section, action, user_id)
VALUES (?1, ?2, ?3, ?4)
`

type RecordSectionApprovalParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Section   string      `json:"section"`
	Action    string      `json:"action"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) RecordSectionApproval(ctx context.Context, arg RecordSectionApprovalParams) error {
	_, err := q.db.ExecContext(ctx, recordSectionApproval,
		arg.SessionID,
		arg.Section,
		arg.Action,
		arg.UserID,
	)
	return err
}

const recordSectionEdit = `-- name: RecordSectionEdit :exec
INSERT INTO scribe_section_edits (session_id, section, content, edited_by)
VALUES (?1, ?2, ?3, ?4)
`

type RecordSectionEditParams struct {
	SessionID pgtype.UUID     `json:"session_id"`
	Section   string          `json:"section"`
	Content   json.RawMessage `json:"content"`
	EditedBy  pgtype.UUID     `json:"edited_by"`
}

func (q *Queries) RecordSectionEdit(ctx context.Context, arg RecordSectionEditParams) error {
	_, err := q.db.ExecContext(ctx, recordSectionEdit,
		arg.SessionID,
		arg.Section,
		arg.Content,
		arg.EditedBy,
	)
	return err
}
