// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scribe_feedback.sql

package database

import (
	"context"

	"github.com/jackc/pgtype"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO scribe_feedback (session_id, section, category, body, user_id)
VALUES (?1, ?2, ?3, ?4, ?5)
RETURNING id, session_id, section, category, body, user_id, at
`

type CreateFeedbackParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Section   string      `json:"section"`
	Category  string      `json:"category"`
	Body      string      `json:"body"`
	UserID    pgtype.UUID `json:"user_id"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (ScribeFeedback, error) {
	row := q.db.QueryRowContext(ctx, createFeedback,
		arg.SessionID,
		arg.Section,
		arg.Category,
		arg.Body,
		arg.UserID,
	)
	var i ScribeFeedback
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Section,
		&i.Category,
		&i.Body,
		&i.UserID,
		&i.At,
	)
	return i, err
}

const getSessionFeedback = `-- name: GetSessionFeedback :many
SELECT f.id, f.session_id, f.section, f.category, f.body, f.user_id, f.at,
       u.name AS author_name
FROM scribe_feedback f
JOIN users u ON u.id = f.user_id
WHERE f.session_id = ?1
ORDER BY f.at ASC
`

type GetSessionFeedbackRow struct {
	ID         pgtype.UUID        `json:"id"`
	SessionID  pgtype.UUID        `json:"session_id"`
	Section    string             `json:"section"`
	Category   string             `json:"category"`
	Body       string             `json:"body"`
	UserID     pgtype.UUID        `json:"user_id"`
	At         pgtype.Timestamptz `json:"at"`
	AuthorName string             `json:"author_name"`
}

func (q *Queries) GetSessionFeedback(ctx context.Context, sessionID pgtype.UUID) ([]GetSessionFeedbackRow, error) {
	rows, err := q.db.QueryContext(ctx, getSessionFeedback, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSessionFeedbackRow{}
	for rows.Next() {
		var i GetSessionFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Section,
			&i.Category,
			&i.Body,
			&i.UserID,
			&i.At,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
