// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scribe_usage.sql

package database

import (
	"context"

	"github.com/jackc/pgtype"
)

const createScribeUsageEvent = `-- name: CreateScribeUsageEvent :one
INSERT INTO scribe_usage_events (
    session_id, event_type, provider, operation, model_id, external_job_id,
    audio_duration_seconds, billable_duration_seconds,
    input_tokens, output_tokens, total_tokens,
    estimated_cost_micros, actual_cost_micros, currency,
    pricing_source, rate_snapshot, metadata
) VALUES (
    ?1, ?2, ?3, ?4, ?5, ?6,
    ?7, ?8,
    ?9, ?10, ?11,
    ?12, ?13, ?14,
    ?15, ?16, ?17
)
RETURNING id, session_id, event_type, provider, operation, model_id, external_job_id, audio_duration_seconds, billable_duration_seconds, input_tokens, output_tokens, total_tokens, estimated_cost_micros, actual_cost_micros, currency, pricing_source, json(rate_snapshot), json(metadata), created_at, updated_at
`

type CreateScribeUsageEventParams struct {
	SessionID               pgtype.UUID    `json:"session_id"`
	EventType               string         `json:"event_type"`
	Provider                string         `json:"provider"`
	Operation               string         `json:"operation"`
	ModelID                 pgtype.Text    `json:"model_id"`
	ExternalJobID           pgtype.Text    `json:"external_job_id"`
	AudioDurationSeconds    pgtype.Numeric `json:"audio_duration_seconds"`
	BillableDurationSeconds pgtype.Int4    `json:"billable_duration_seconds"`
	InputTokens             pgtype.Int4    `json:"input_tokens"`
	OutputTokens            pgtype.Int4    `json:"output_tokens"`
	TotalTokens             pgtype.Int4    `json:"total_tokens"`
	EstimatedCostMicros     int64          `json:"estimated_cost_micros"`
	ActualCostMicros        pgtype.Int8    `json:"actual_cost_micros"`
	Currency                string         `json:"currency"`
	PricingSource           string         `json:"pricing_source"`
	RateSnapshot            pgtype.JSONB   `json:"rate_snapshot"`
	Metadata                pgtype.JSONB   `json:"metadata"`
}

func (q *Queries) CreateScribeUsageEvent(ctx context.Context, arg CreateScribeUsageEventParams) (ScribeUsageEvent, error) {
	row := q.db.QueryRowContext(ctx, createScribeUsageEvent,
		arg.SessionID,
		arg.EventType,
		arg.Provider,
		arg.Operation,
		arg.ModelID,
		arg.ExternalJobID,
		arg.AudioDurationSeconds,
		arg.BillableDurationSeconds,
		arg.InputTokens,
		arg.OutputTokens,
		arg.TotalTokens,
		arg.EstimatedCostMicros,
		arg.ActualCostMicros,
		arg.Currency,
		arg.PricingSource,
		arg.RateSnapshot,
		arg.Metadata,
	)
	var i ScribeUsageEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EventType,
		&i.Provider,
		&i.Operation,
		&i.ModelID,
		&i.ExternalJobID,
		&i.AudioDurationSeconds,
		&i.BillableDurationSeconds,
		&i.InputTokens,
		&i.OutputTokens,
		&i.TotalTokens,
		&i.EstimatedCostMicros,
		&i.ActualCostMicros,
		&i.Currency,
		&i.PricingSource,
		&i.RateSnapshot,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScribeUsageSummaryForSession = `-- name: GetScribeUsageSummaryForSession :one
WITH session_usage_events AS (
    SELECT id, session_id, event_type, provider, operation, model_id, external_job_id, audio_duration_seconds, billable_duration_seconds, input_tokens, output_tokens, total_tokens, estimated_cost_micros, actual_cost_micros, currency, pricing_source, json(rate_snapshot), json(metadata), created_at, updated_at
    FROM scribe_usage_events
    WHERE session_id = ?1
)
SELECT
    CAST(COUNT(*) AS integer) AS event_count,
    CAST(COALESCE(SUM(estimated_cost_micros), 0) AS bigint) AS total_estimated_cost_micros,
    (
        SELECT total_actual_cost_micros
        FROM (
            SELECT NULL AS total_actual_cost_micros
            WHERE NOT EXISTS (SELECT 1 FROM session_usage_events WHERE actual_cost_micros IS NOT NULL)
            UNION ALL
            SELECT CAST(SUM(actual_cost_micros) AS bigint) AS total_actual_cost_micros
            FROM session_usage_events
            WHERE actual_cost_micros IS NOT NULL
        ) actual_cost_summary
        LIMIT 1
    ) AS total_actual_cost_micros,
    (SUM(audio_duration_seconds) FILTER (WHERE event_type = 'transcription')) AS transcription_audio_duration_seconds,
    (
        SELECT transcription_billable_duration_seconds
        FROM (
            SELECT NULL AS transcription_billable_duration_seconds
            WHERE NOT EXISTS (SELECT 1 FROM session_usage_events WHERE event_type = 'transcription' AND billable_duration_seconds IS NOT NULL)
            UNION ALL
            SELECT CAST(SUM(billable_duration_seconds) AS bigint) AS transcription_billable_duration_seconds
            FROM session_usage_events
            WHERE event_type = 'transcription' AND billable_duration_seconds IS NOT NULL
        ) billable_duration_summary
        LIMIT 1
    ) AS transcription_billable_duration_seconds,
    COALESCE(SUM(estimated_cost_micros) FILTER (WHERE event_type = 'transcription'), 0) AS transcription_estimated_cost_micros,
    (
        SELECT transcription_actual_cost_micros
        FROM (
            SELECT NULL AS transcription_actual_cost_micros
            WHERE NOT EXISTS (SELECT 1 FROM session_usage_events WHERE event_type = 'transcription' AND actual_cost_micros IS NOT NULL)
            UNION ALL
            SELECT CAST(SUM(actual_cost_micros) AS bigint) AS transcription_actual_cost_micros
            FROM session_usage_events
            WHERE event_type = 'transcription' AND actual_cost_micros IS NOT NULL
        ) transcription_actual_cost_summary
        LIMIT 1
    ) AS transcription_actual_cost_micros,
    CASE WHEN COUNT(DISTINCT provider) FILTER (WHERE event_type = 'transcription') = 1 THEN MIN(provider) FILTER (WHERE event_type = 'transcription')
         WHEN COUNT(*) FILTER (WHERE event_type = 'transcription') > 1 THEN 'multiple'
         ELSE NULL END AS transcription_provider,
    CASE WHEN COUNT(DISTINCT operation) FILTER (WHERE event_type = 'transcription') = 1 THEN MIN(operation) FILTER (WHERE event_type = 'transcription')
         WHEN COUNT(*) FILTER (WHERE event_type = 'transcription') > 1 THEN 'multiple'
         ELSE NULL END AS transcription_operation,
    COALESCE(SUM(input_tokens) FILTER (WHERE event_type = 'llm'), 0) AS llm_input_tokens,
    COALESCE(SUM(output_tokens) FILTER (WHERE event_type = 'llm'), 0) AS llm_output_tokens,
    COALESCE(SUM(total_tokens) FILTER (WHERE event_type = 'llm'), 0) AS llm_total_tokens,
    COALESCE(SUM(estimated_cost_micros) FILTER (WHERE event_type = 'llm'), 0) AS llm_estimated_cost_micros,
    (
        SELECT llm_actual_cost_micros
        FROM (
            SELECT NULL AS llm_actual_cost_micros
            WHERE NOT EXISTS (SELECT 1 FROM session_usage_events WHERE event_type = 'llm' AND actual_cost_micros IS NOT NULL)
            UNION ALL
            SELECT CAST(SUM(actual_cost_micros) AS bigint) AS llm_actual_cost_micros
            FROM session_usage_events
            WHERE event_type = 'llm' AND actual_cost_micros IS NOT NULL
        ) llm_actual_cost_summary
        LIMIT 1
    ) AS llm_actual_cost_micros,
    CASE WHEN COUNT(DISTINCT provider) FILTER (WHERE event_type = 'llm') = 1 THEN MIN(provider) FILTER (WHERE event_type = 'llm')
         WHEN COUNT(*) FILTER (WHERE event_type = 'llm') > 1 THEN 'multiple'
         ELSE NULL END AS llm_provider,
    CASE WHEN COUNT(DISTINCT operation) FILTER (WHERE event_type = 'llm') = 1 THEN MIN(operation) FILTER (WHERE event_type = 'llm')
         WHEN COUNT(*) FILTER (WHERE event_type = 'llm') > 1 THEN 'multiple'
         ELSE NULL END AS llm_operation,
    CASE WHEN COUNT(*) FILTER (WHERE event_type = 'llm') > 0
          AND COUNT(model_id) FILTER (WHERE event_type = 'llm') = COUNT(*) FILTER (WHERE event_type = 'llm')
          AND COUNT(DISTINCT model_id) FILTER (WHERE event_type = 'llm') = 1
         THEN MIN(model_id) FILTER (WHERE event_type = 'llm')
         ELSE NULL END AS llm_model_id,
    CAST(COUNT(*) FILTER (WHERE actual_cost_micros IS NOT NULL) AS integer) AS actual_event_count
FROM session_usage_events
`

type GetScribeUsageSummaryForSessionRow struct {
	EventCount                           int64       `json:"event_count"`
	TotalEstimatedCostMicros             int64       `json:"total_estimated_cost_micros"`
	TotalActualCostMicros                interface{} `json:"total_actual_cost_micros"`
	TranscriptionAudioDurationSeconds    interface{} `json:"transcription_audio_duration_seconds"`
	TranscriptionBillableDurationSeconds interface{} `json:"transcription_billable_duration_seconds"`
	TranscriptionEstimatedCostMicros     interface{} `json:"transcription_estimated_cost_micros"`
	TranscriptionActualCostMicros        interface{} `json:"transcription_actual_cost_micros"`
	TranscriptionProvider                interface{} `json:"transcription_provider"`
	TranscriptionOperation               interface{} `json:"transcription_operation"`
	LlmInputTokens                       interface{} `json:"llm_input_tokens"`
	LlmOutputTokens                      interface{} `json:"llm_output_tokens"`
	LlmTotalTokens                       interface{} `json:"llm_total_tokens"`
	LlmEstimatedCostMicros               interface{} `json:"llm_estimated_cost_micros"`
	LlmActualCostMicros                  interface{} `json:"llm_actual_cost_micros"`
	LlmProvider                          interface{} `json:"llm_provider"`
	LlmOperation                         interface{} `json:"llm_operation"`
	LlmModelID                           interface{} `json:"llm_model_id"`
	ActualEventCount                     int64       `json:"actual_event_count"`
}

func (q *Queries) GetScribeUsageSummaryForSession(ctx context.Context, sessionID pgtype.UUID) (GetScribeUsageSummaryForSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getScribeUsageSummaryForSession, sessionID)
	var i GetScribeUsageSummaryForSessionRow
	err := row.Scan(
		&i.EventCount,
		&i.TotalEstimatedCostMicros,
		&i.TotalActualCostMicros,
		&i.TranscriptionAudioDurationSeconds,
		&i.TranscriptionBillableDurationSeconds,
		&i.TranscriptionEstimatedCostMicros,
		&i.TranscriptionActualCostMicros,
		&i.TranscriptionProvider,
		&i.TranscriptionOperation,
		&i.LlmInputTokens,
		&i.LlmOutputTokens,
		&i.LlmTotalTokens,
		&i.LlmEstimatedCostMicros,
		&i.LlmActualCostMicros,
		&i.LlmProvider,
		&i.LlmOperation,
		&i.LlmModelID,
		&i.ActualEventCount,
	)
	return i, err
}

const listScribeUsageEventsForSession = `-- name: ListScribeUsageEventsForSession :many
SELECT id, session_id, event_type, provider, operation, model_id, external_job_id, audio_duration_seconds, billable_duration_seconds, input_tokens, output_tokens, total_tokens, estimated_cost_micros, actual_cost_micros, currency, pricing_source, json(rate_snapshot), json(metadata), created_at, updated_at
FROM scribe_usage_events
WHERE session_id = ?1
ORDER BY created_at ASC
`

func (q *Queries) ListScribeUsageEventsForSession(ctx context.Context, sessionID pgtype.UUID) ([]ScribeUsageEvent, error) {
	rows, err := q.db.QueryContext(ctx, listScribeUsageEventsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScribeUsageEvent{}
	for rows.Next() {
		var i ScribeUsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventType,
			&i.Provider,
			&i.Operation,
			&i.ModelID,
			&i.ExternalJobID,
			&i.AudioDurationSeconds,
			&i.BillableDurationSeconds,
			&i.InputTokens,
			&i.OutputTokens,
			&i.TotalTokens,
			&i.EstimatedCostMicros,
			&i.ActualCostMicros,
			&i.Currency,
			&i.PricingSource,
			&i.RateSnapshot,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
