// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scribe.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createScribeSession = `-- name: CreateScribeSession :one
INSERT INTO scribe_sessions (tenant_id, user_id, patient_id, encounter_id, department_id, status)
VALUES ($1, $2, $3, $4, $5, 'processing')
RETURNING id, tenant_id, user_id, patient_id, encounter_id, department_id, status,
          transcript, ai_output, error_message, started_at, stopped_at, completed_at, created_at
`

type CreateScribeSessionParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	UserID       pgtype.UUID `json:"user_id"`
	PatientID    string      `json:"patient_id"`
	EncounterID  string      `json:"encounter_id"`
	DepartmentID string      `json:"department_id"`
}

func (q *Queries) CreateScribeSession(ctx context.Context, arg CreateScribeSessionParams) (ScribeSession, error) {
	row := q.db.QueryRow(ctx, createScribeSession,
		arg.TenantID,
		arg.UserID,
		arg.PatientID,
		arg.EncounterID,
		arg.DepartmentID,
	)
	var i ScribeSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PatientID,
		&i.EncounterID,
		&i.DepartmentID,
		&i.Status,
		&i.Transcript,
		&i.AiOutput,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScribeSession = `-- name: GetScribeSession :one
SELECT id, tenant_id, user_id, patient_id, encounter_id, department_id, status,
       transcript, ai_output, error_message, started_at, stopped_at, completed_at, created_at
FROM scribe_sessions
WHERE id = $1 AND tenant_id = $2
`

type GetScribeSessionParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetScribeSession(ctx context.Context, arg GetScribeSessionParams) (ScribeSession, error) {
	row := q.db.QueryRow(ctx, getScribeSession, arg.ID, arg.TenantID)
	var i ScribeSession
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.PatientID,
		&i.EncounterID,
		&i.DepartmentID,
		&i.Status,
		&i.Transcript,
		&i.AiOutput,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.StoppedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listScribeSessions = `-- name: ListScribeSessions :many
SELECT id, tenant_id, user_id, patient_id, encounter_id, department_id, status,
       error_message, started_at, stopped_at, completed_at, created_at
FROM scribe_sessions
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT 50
`

type ListScribeSessionsRow struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PatientID    string             `json:"patient_id"`
	EncounterID  string             `json:"encounter_id"`
	DepartmentID string             `json:"department_id"`
	Status       string             `json:"status"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	StoppedAt    pgtype.Timestamptz `json:"stopped_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListScribeSessions(ctx context.Context, tenantID pgtype.UUID) ([]ListScribeSessionsRow, error) {
	rows, err := q.db.Query(ctx, listScribeSessions, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScribeSessionsRow{}
	for rows.Next() {
		var i ListScribeSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.PatientID,
			&i.EncounterID,
			&i.DepartmentID,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.StoppedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScribeSessionComplete = `-- name: UpdateScribeSessionComplete :exec
UPDATE scribe_sessions
SET status = 'complete', ai_output = $3, completed_at = now()
WHERE id = $1 AND tenant_id = $2
`

type UpdateScribeSessionCompleteParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	AiOutput []byte      `json:"ai_output"`
}

func (q *Queries) UpdateScribeSessionComplete(ctx context.Context, arg UpdateScribeSessionCompleteParams) error {
	_, err := q.db.Exec(ctx, updateScribeSessionComplete, arg.ID, arg.TenantID, arg.AiOutput)
	return err
}

const updateScribeSessionError = `-- name: UpdateScribeSessionError :exec
UPDATE scribe_sessions
SET status = 'error', error_message = $3
WHERE id = $1 AND tenant_id = $2
`

type UpdateScribeSessionErrorParams struct {
	ID           pgtype.UUID `json:"id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateScribeSessionError(ctx context.Context, arg UpdateScribeSessionErrorParams) error {
	_, err := q.db.Exec(ctx, updateScribeSessionError, arg.ID, arg.TenantID, arg.ErrorMessage)
	return err
}

const updateScribeSessionProcessing = `-- name: UpdateScribeSessionProcessing :exec
UPDATE scribe_sessions
SET status = 'processing', transcript = $3
WHERE id = $1 AND tenant_id = $2
`

type UpdateScribeSessionProcessingParams struct {
	ID         pgtype.UUID `json:"id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	Transcript pgtype.Text `json:"transcript"`
}

func (q *Queries) UpdateScribeSessionProcessing(ctx context.Context, arg UpdateScribeSessionProcessingParams) error {
	_, err := q.db.Exec(ctx, updateScribeSessionProcessing, arg.ID, arg.TenantID, arg.Transcript)
	return err
}
