// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (name, athena_practice_id)
VALUES ($1, $2)
RETURNING id, name, athena_practice_id, created_at, updated_at
`

type CreateTenantParams struct {
	Name             string      `json:"name"`
	AthenaPracticeID pgtype.Text `json:"athena_practice_id"`
}

type CreateTenantRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	AthenaPracticeID pgtype.Text        `json:"athena_practice_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (CreateTenantRow, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.AthenaPracticeID)
	var i CreateTenantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AthenaPracticeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, athena_practice_id, created_at, updated_at
FROM tenants
WHERE id = $1
`

type GetTenantByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	AthenaPracticeID pgtype.Text        `json:"athena_practice_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (GetTenantByIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i GetTenantByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AthenaPracticeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByName = `-- name: GetTenantByName :one
SELECT id, name, athena_practice_id, created_at, updated_at
FROM tenants
WHERE name = $1
`

type GetTenantByNameRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	AthenaPracticeID pgtype.Text        `json:"athena_practice_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTenantByName(ctx context.Context, name string) (GetTenantByNameRow, error) {
	row := q.db.QueryRow(ctx, getTenantByName, name)
	var i GetTenantByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AthenaPracticeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
