root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/janushc-dash"
  cmd = "go build -o ./tmp/janushc-dash ./cmd/janushc-dash"
  delay = 1000
  exclude_dir = ["tmp", "web", "node_modules", ".devcontainer", "docs"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "sql"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
